source:         .
destination:    ./_site

markdown:       marku
pygments:       true

plugins:    ./_plugins

permalink: /:month-:day-:year/:title.html

base_url:        /

rdiscount:
  extensions: []
