source:         .
destination:    ./_site
includes:       ./_includes

markdown:       rdiscount
pygments:       true

base_url:       http://kyleberry.org
description:    "Kyle's Blog"
root_desc:      "Kyle's Blog"
